# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:

jobs:
  release-project:
    name: Release Static site to Github Releasess
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: reactive
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: reactive.zip
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./reactive.zip
          asset_name: reactive-v${{ github.run_number }}.zip
          asset_content_type: application/zip
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build:lightdm

      - name: Upload static site
        uses: actions/upload-artifact@v2
        with:
          name: reactive
          path: reactive/
